# -*- coding: utf-8 -*-
"""numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkMe7XyofDK4HJT2bm6l22ac6nVGV8Ej
"""

import pandas as pd
import numpy as np

data=pd.read_excel("numbers.xlsx")

data["Numbers"]

for i in data["Numbers"]:
    if i % 2 == 0:
        print(f"Even Number: {i}")
    else:
        print(f"odd number: {i}")

    if i <= 1:
      print(f"{i} is not a prime number.")
    else:
      is_prime = True
    for j in range(2, i):
        if i % j == 0:
            is_prime = False
            break

    if is_prime:
        print(f"{i} is a prime number.")
    else:
        print(f"{i} is not a prime number.")

    print("***************************")

sum_of_digits=0
for i in range(11):
  digit = i % 10  # Get the last digit
  sum_of_digits += digit  # Add the digit to the sum
  i //= 10

print(sum_of_digits)

len(data["Numbers"])



